### ISSUE TITLE
如何使用颜色？

### ISSUE THREAD

**Issue by lclty** [baobao1270/awsl.css#1]
我尝试了在<div class="">标签中添加了“--aw-color-luotianyi”，但是不起作用，而“aw-color-luotianyi”也不起作用。

**Comment by lclty** [comment]
hmmm，中间有一个标签忘了加代码框了（没想到Gayhub竟然能自动识别HTML）
`<div class="">`

**Comment by baobao1270** [comment]
1. `--aw-color` 开头的是 css 变量，请阅读 [MDN 上有关 CSS 变量的说明](https://developer.mozilla.org/zh-CN/docs/Web/CSS/Using_CSS_custom_properties)
2. 如需针对 class 设置，请使用 `class="aw-bg-lightblue"`。

**Comment by lclty** [comment]
Thank you！
